# Generated by Django 5.1.3 on 2024-11-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_quiz_song_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='song_file',
            field=models.FileField(upload_to='short_songs/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to='full_songs/'),
        ),
    ]
