# Generated by Django 5.1.3 on 2024-11-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_quiz_options_alter_song_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.AddField(
            model_name='song',
            name='user_genre',
            field=models.CharField(blank=True, choices=[('rock', 'Рок'), ('romance', 'Шансон'), ('hip_hop', 'Хип-хоп'), ('disco', 'Диско'), ('dance', 'Танец'), ('pop', 'Поп'), ('ballad', 'Баллада'), ('rap', 'Рэп'), ('funk', 'Фанк'), ('jazz', 'Джаз')], max_length=10, null=True),
        ),
    ]
