# Generated by Django 5.1.3 on 2024-11-26 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_song_genre_song_user_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='user_genre',
            new_name='song_genre',
        ),
    ]
