# Generated by Django 5.1.3 on 2024-11-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_user_genre_song_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_genre',
            field=models.CharField(blank=True, choices=[('rock', 'Рок'), ('romance', 'Шансон'), ('hip_hop', 'Хип-хоп'), ('disco', 'Диско'), ('dance', 'Танец'), ('pop', 'Поп'), ('ballad', 'Баллада'), ('rap', 'Рэп'), ('funk', 'Фанк'), ('jazz', 'Джаз'), ('house', 'Хаус')], max_length=10, null=True),
        ),
    ]
