# Generated by Django 5.1.3 on 2024-11-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_favoritesong'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritesong',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterField(
            model_name='song',
            name='song_genre',
            field=models.CharField(blank=True, choices=[('rock', 'Рок'), ('romance', 'Шансон'), ('hip_hop', 'Хип-хоп'), ('disco', 'Диско'), ('dance', 'Танец'), ('pop', 'Поп'), ('ballad', 'Баллада'), ('rap', 'Рэп'), ('funk', 'Фанк'), ('jazz', 'Джаз'), ('house', 'Хаус'), ('edm', 'Электро'), ('bandstand', 'Эстрада')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='user_genre',
            field=models.CharField(blank=True, choices=[('rock', 'Рок'), ('romance', 'Шансон'), ('hip_hop', 'Хип-хоп'), ('disco', 'Диско'), ('dance', 'Танец'), ('pop', 'Поп'), ('ballad', 'Баллада'), ('rap', 'Рэп'), ('funk', 'Фанк'), ('jazz', 'Джаз'), ('house', 'Хаус'), ('edm', 'Электро'), ('bandstand', 'Эстрада')], max_length=10, null=True),
        ),
    ]
