# Generated by Django 5.1.3 on 2024-11-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_favoritesong_options_alter_song_song_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_genre',
            field=models.CharField(blank=True, choices=[('rock', 'Рок'), ('romance', 'Шансон'), ('hip_hop', 'Хип-хоп'), ('disco', 'Диско'), ('dance', 'Танец'), ('pop', 'Поп'), ('ballad', 'Баллада'), ('rap', 'Рэп'), ('funk', 'Фанк'), ('jazz', 'Джаз'), ('house', 'Хаус'), ('edm', 'Электро'), ('bandstand', 'Эстрада'), ('hifi', 'Хай-фай')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='user_genre',
            field=models.CharField(blank=True, choices=[('rock', 'Рок'), ('romance', 'Шансон'), ('hip_hop', 'Хип-хоп'), ('disco', 'Диско'), ('dance', 'Танец'), ('pop', 'Поп'), ('ballad', 'Баллада'), ('rap', 'Рэп'), ('funk', 'Фанк'), ('jazz', 'Джаз'), ('house', 'Хаус'), ('edm', 'Электро'), ('bandstand', 'Эстрада'), ('hifi', 'Хай-фай')], max_length=10, null=True),
        ),
    ]
