# Generated by Django 5.1.3 on 2024-11-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_song_song_genre_alter_stats_user_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_genre',
            field=models.CharField(blank=True, choices=[('rock', 'Рок'), ('romance', 'Шансон'), ('disco', 'Диско'), ('dance', 'Танец'), ('pop', 'Поп'), ('rap', 'Рэп'), ('house', 'Хаус'), ('edm', 'Электро'), ('bandstand', 'Эстрада')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='user_genre',
            field=models.CharField(blank=True, choices=[('rock', 'Рок'), ('romance', 'Шансон'), ('disco', 'Диско'), ('dance', 'Танец'), ('pop', 'Поп'), ('rap', 'Рэп'), ('house', 'Хаус'), ('edm', 'Электро'), ('bandstand', 'Эстрада')], max_length=10, null=True),
        ),
    ]
