# Generated by Django 5.1.3 on 2024-11-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_song_play_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='user_genre',
            new_name='first_user_genre',
        ),
        migrations.AddField(
            model_name='stats',
            name='second_user_genre',
            field=models.CharField(blank=True, choices=[('rock', 'Рок'), ('romance', 'Шансон'), ('disco', 'Диско'), ('dance', 'Танец'), ('pop', 'Поп'), ('rap', 'Рэп'), ('house', 'Хаус'), ('edm', 'Электро'), ('bandstand', 'Эстрада')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='third_user_genre',
            field=models.CharField(blank=True, choices=[('rock', 'Рок'), ('romance', 'Шансон'), ('disco', 'Диско'), ('dance', 'Танец'), ('pop', 'Поп'), ('rap', 'Рэп'), ('house', 'Хаус'), ('edm', 'Электро'), ('bandstand', 'Эстрада')], max_length=10, null=True),
        ),
    ]
