# Generated by Django 5.1.3 on 2024-11-22 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quiz_type', models.CharField(choices=[('title', 'Название'), ('composer', 'Композитор'), ('genre', 'Жанр')], max_length=10)),
                ('difficulty', models.CharField(choices=[('easy', 'Легко'), ('hard', 'Сложно')], max_length=4)),
                ('song_file', models.FileField(upload_to='songs/')),
                ('correct_answer', models.CharField(max_length=255)),
                ('wrong_answer1', models.CharField(max_length=255)),
                ('wrong_answer2', models.CharField(max_length=255)),
                ('wrong_answer3', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=100)),
                ('attempts', models.IntegerField(default=3)),
                ('last_reset_date', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
