# Generated by Django 5.1.3 on 2024-11-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_quiz_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='song_file',
            field=models.FileField(upload_to='quiz_songs/'),
        ),
    ]
