# Generated by Django 5.1.3 on 2024-11-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_quiz_song_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='song_file',
            field=models.FileField(upload_to='songs/'),
        ),
    ]
