# Generated by Django 5.1.3 on 2024-11-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_quiz_song_file_alter_song_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Викторина', 'verbose_name_plural': 'Викторины'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'Музыка', 'verbose_name_plural': 'Музыка'},
        ),
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
        migrations.AddField(
            model_name='stats',
            name='user_genre',
            field=models.CharField(blank=True, choices=[('rock', 'Рок'), ('romance', 'Шансон'), ('hip_hop', 'Хип-хоп'), ('disco', 'Диско'), ('dance', 'Танец'), ('pop', 'Поп'), ('ballad', 'Баллада'), ('rap', 'Рэп'), ('funk', 'Фанк'), ('jazz', 'Джаз')], max_length=10, null=True),
        ),
    ]
